# Docker Compose configuration for Quick Prompt Box
services:
  app:
    build: .                                          # Build from local Dockerfile
    ports:
      - "${PORT:-3131}:${PORT:-3131}"                # Map host port to container port
    environment:
      - PORT=${PORT:-3131}                           # Application port
      - HOST=${HOST:-0.0.0.0}                        # Bind address
    restart: unless-stopped                          # Auto-restart on failure
    healthcheck:                                     # Health monitoring
      test: ["CMD", "sh", "-c", "nc -z localhost ${PORT:-3131} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
