// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bixzwdvfwxlzrhxdfzgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpeHp3ZHZmd3hsenJoeGRmemd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTAyMDEsImV4cCI6MjA2OTQyNjIwMX0.yyOaEE2z9Yzqyg6sSdaAIGtVz_z1MSxvI6rJ-R6I39A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});